node {
    def app
    withCredentials([[
        $class: 'FileBinding',
        credentialsId: 'yamato-alpha-deploykey',
        variable: 'YAMATO_DEPLOY_KEY'
    ]]) {
        stage('Deploy') {
            docker.image('ubuntu').inside("-v $YAMATO_DEPLOY_KEY:/src/deploy_key.pem"){
                sh 'chmod 400 /src/deploy_key.pem'
                sh 'cat /src/deploy_key.pem'
                //sh 'ssh -i /src/deploy_key.pem yamatoadmin@alpha-aws-yamato.trendops.co "sudo salt '*api*' cmd.run 'ifconfig'"'
            }
        }
    }
} 
